### ISSUE TITLE
Streamline SuperOffice Environment enumerations

### ISSUE THREAD

**Issue by stonesvillage** [SuperOffice/SuperOffice.WebApi-Samples#2]
Hi,
I've been using the SuperOffice OAuth package for a while (great addition to the SuperOffice eco system!) and when testing the new WebApi Client I notice that the SuperOffice environment enumerations differs between the packages which result in code like this:
```C#
private static OnlineEnvironment MapOnlineEnvironment(SuperOfficeAuthenticationEnvironment environment)
{
	return environment switch
	{
		SuperOfficeAuthenticationEnvironment.Development => OnlineEnvironment.SOD,
		SuperOfficeAuthenticationEnvironment.Stage => OnlineEnvironment.Stage,
		SuperOfficeAuthenticationEnvironment.Production => OnlineEnvironment.Production,
		_ => throw new NotSupportedException($"Not supported...")
	};
}
```
Whould it be possible to streamline the environment enumerations (probably requires a "Core" package that both SuperOffice OAuth and WebApi Client depends on).
Or are the enumerations separated of another reason perhaps?

Best regards

Gunnar Stensby, i-Centrum AB

**Comment by AnthonyYates** [comment]
Thanks for the suggestion Gunnar. Because these libraries do share some things besides this enumeration, such as constants, it might make sense to split them up as suggested. However, that's a pretty extreme thing to do for these very independent libraries. 

I'm starting to think maybe constant strings would of been better for both. Keep it simple, at least for the consumer. But, as there would be greater odds for incorrect inputs, would require more validation. 

I think we might have to live with this one subtle inconvenience for the time being.

**Comment by AnthonyYates** [comment]
Haven't heard back from Gunnar, so closing this issue.

**Comment by AnthonyYates** [comment]
@stonesvillage, if we are to move forward on this, the solution we think is right would be to add a dependency to the AspNet.Security.OAuth.SuperOffice library and used the types from it. Admittedly, there are some shared constants that we could eliminate in the SuperOffice.WebApi, and used from the OAuth lib... Does that sound reasonable?

**Comment by stonesvillage** [comment]
Hi,

I saw a comment on this issue in my mail but it seems like it has been removed.
From the email I see that you were thinking about to "_add a dependency to the AspNet.Security.OAuth.SuperOffice library and used the types from it_".
I think that's a good idea and something that you can do without too much hassle since your're in preview.
Both libraries handles authentication which makes the dependency a natural addition.

**Comment by AnthonyYates** [comment]
> From the email I see that you were thinking about to "_add a dependency to the AspNet.Security.OAuth.SuperOffice library and used the types from it_".
> I think that's a good idea and something that you can do without too much hassle since your're in preview.
> Both libraries handles authentication which makes the dependency a natural addition.

Yes, we discussed it and were going to do that. I was happy to share the news with you. Unfortunately I completely forgot SuperOffice.WebApi is .NetStandard 2.0 and AspNet.Security.OAuth.SuperOffice is .net 3.1 (now 5.0). 

Because we want SuperOffice.WebApi to stay backwards compatibility between the old and the new, taking a dependency like that isn't possible. Sorry.

**Comment by stonesvillage** [comment]
I see, makes sense 👍

Then the only way around it is the "Core" package I mentioned earlier.
Personally I think it's worth the hassle because you will always have common stuff that many packages needs.
The different SuperOffice environments is one example, authentication (OAuth tokens, claims etc.) is another.
The netserver packages depends on a Core package, I think the same goes for the webapi eco system you have started on.

Anyway - thanks for quick feedback!

PS
Any chances that this package will become open source?
It's so much easier to evaluate and learn when you can read the code :)
DS

**Comment by AnthonyYates** [comment]
> Any chances that this package will become open source?

We did discuss it...and I would like to, however, because all of the Agent and Carriers are generated this is highly unlikely. 
Most honestly, we don't have the resources to keep all the existing samples up-to-date and most certainly would not be able to properly manage an open source project as such.

Time and resources may tell a different story.
